// <auto-generated />
using System;
using FitnessCalendar.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessCalendar.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessCalendar.Models.FitnessRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FullBodyTrainingId")
                        .HasColumnType("int");

                    b.Property<int?>("StretchingId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FullBodyTrainingId");

                    b.HasIndex("StretchingId");

                    b.ToTable("FitnessRecords");
                });

            modelBuilder.Entity("FitnessCalendar.Models.TrainingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TrainingTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Тренировка всего тела",
                            Name = "FullBody"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Растяжка",
                            Name = "Stretching"
                        });
                });

            modelBuilder.Entity("FitnessCalendar.Models.FitnessRecord", b =>
                {
                    b.HasOne("FitnessCalendar.Models.TrainingType", "FullBodyTraining")
                        .WithMany()
                        .HasForeignKey("FullBodyTrainingId");

                    b.HasOne("FitnessCalendar.Models.TrainingType", "Stretching")
                        .WithMany()
                        .HasForeignKey("StretchingId");

                    b.Navigation("FullBodyTraining");

                    b.Navigation("Stretching");
                });
#pragma warning restore 612, 618
        }
    }
}
